name: Deploy Sms-Valet-App

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    name: Upload Scripts To PI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v3

      - name: Upload
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.IP_ADDR }}
          username: ${{ secrets.USER }}
          port: ${{ secrets.PORT }}
          password: ${{ secrets.SSH_PASS }}
          source: "./test_folder/"
          target: "/home/pi/git_upload"